
services:
  backend:
    image: niasai/welfare-app:old
    container_name: welfare-backend
    ports:
      - "1542:1542" 
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/welfare_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&jdbcCompliantTruncation=false&allowMultiQueries=true
      - SPRING_DATASOURCE_USERNAME=welfare_user
      - SPRING_DATASOURCE_PASSWORD=y+7pm-8bh!CO*sW?R>-6
    networks:
      - welfare-net

  db:
    image: mysql:8.0
    container_name: welfare-mysql
    restart: always
    environment:
      MYSQL_DATABASE: welfare_data
      MYSQL_USER: welfare_user
      MYSQL_PASSWORD: y+7pm-8bh!CO*sW?R>-6
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    ports:
      - "1543:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - welfare-net
networks:
  welfare-net:
    driver: bridge

volumes:
  mysql-data: